[package]
name = "snocat"
description = "Streaming Network Overlay Connection Arbitration Tunnel"
version = "0.1.2"
authors = ["Microsoft Corporation", "Zoey <Dessix@Dessix.net>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/microsoft/snocat"
categories = ["network-programming"]
include = ["src/**/*", "build.rs", "Cargo.toml", "LICENSE*", "*.md"]

[dependencies]
anyhow = "~1.0.38"
ffi-support = "0.4.2"
futures = "^0.3.12"
futures-io = "^0.3.12"
gen-z = "~0.1.0"
lazy_static = "1.4.0"
log = "~0.4.13"
prost = "^0.7.0"
prost-types = "^0.7.0"
quinn = "~0.7"
serde = { version = "~1.0.123", features=["derive"] }
serde_json = "~1.0.59"
thiserror = "^1.0.24"
tracing = "~0.1.22"
tracing-futures = "~0.2.4"
tracing-subscriber = "~0.2.15"
tokio = { version = "^1.3", features=["net", "io-util", "signal", "sync", "time", "macros", "rt-multi-thread"] }
tokio-stream = { version = "^0.1.4", features=["net", "io-util"] }
tonic = { version = "^0.4.0" }
triggered = "~0.1.1"

[build-dependencies]
prost-build = "^0.7.0"
tonic-build = "^0.4.0"

[lib]
crate-type = ["rlib", "cdylib"]

[features]
default = ["core"]
core = []
ffi = ["core"]

full = ["core", "ffi"]
