[package]
name = "snocat-cli"
description = "Streaming Network Overlay Connection Arbitration Tunnel"
version = "0.1.2"
authors = ["Microsoft Corporation", "Zoey <Dessix@Dessix.net>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/microsoft/snocat"
categories = ["network-programming", "command-line-utilities"]
include = ["src/**/*", "build.rs", "Cargo.toml", "LICENSE*", "*.md"]

[dependencies]
snocat = { version = "^0.1.1" }
anyhow = "~1.0.38"
clap = "~2.33.3"
futures = "^0.3.12"
futures-io = "^0.3.12"
gen-z = "~0.1.0"
log = "~0.4.13"
quinn = "~0.7"
rcgen = "0.8"
tracing = "~0.1.22"
tracing-futures = "~0.2.4"
tracing-subscriber = "~0.2.15"
tokio = { version = "^1.3", features=["net", "io-util", "signal", "macros"] }
tokio-stream = { version = "^0.1.4", features=["net", "io-util"] }
triggered = "~0.1.1"
